### ISSUE TITLE
Guidance on opening the whole house transmitter.

### ISSUE THREAD

**Issue by meesern** [JackKelly/rfm_edf_ecomanager#1]
Hi, thanks it's brilliant to have the photo's and that understanding of the wireless code.  I'm hacking for an energy monitoring project with Horizon Digital Economy research institute at the University of Nottingham.

I find the transmitter box clicks apart easily except would not part at two points a third of the way down from the top.  I can see now that it's due to two legs which fit into the two hollow pillars.   By the feel of it I was expecting screws but it was clear that there weren't any so I assumed glue.  Did you have any trouble parting the case at that point?  Are those legs glued in perhaps and did you use any particular tool or technique to get in?

Fascinating that the black areal is fake - it explains the odd feel of its rotation.

**Comment by JackKelly** [comment]
Hi Rupert,

Sounds like an interesting project!

If I remember correctly, my Current Cost "sensable" transmitter just clicked apart: I don't remember having to undo any screws: I think I just forced a flat-head screwdriver into the gap between the top and bottom halves and teased it apart.  But I was probably quite heavy-handed with mine ;).

Thanks,
Jack

**Comment by meesern** [comment]
Thanks, there wasn't glue and it did open with a bit of creaking and groaning.  It helped to know what was happening.  One curious thing though.  The transmitter range seems only to be a few inches.  If I place the CC-128 display further than about six inches away from the transmitter the display goes to all dashes.  Signal strength display shows full strength whenever a reading in displayed (and nothing when it is not).  It can't be general interference because I have three socket transmitters that are detected just fine in other rooms.  I noticed this when the box was half open and assumed that it was because the connection to the black antenna was disturbed but since it turns out that this is not connected in any case I guess it's not that.    The actual antenna seems to have a good connection.  I mention it here just in case it rings any bells with anyone else.

The project is an interesting one - looking at disaggregating and visualising office energy consumption in novel ways that promote engagement and a personal relationship to the energy consumption. 

More specifically a couple of questions... 
Your description of the wireless format shows only 12 bits of data per sensor/clamp from the whole house transmitter.  If the units are watts the range would only be 1W to 4K96W  which does not seem right.  Colleges have seen the unit report over 12KW.

The PIC micro has a number of 10bit ADC's.  Have you found how the ADC's are wired to the sensor?  If they use only one ADC per sensor/clamp then there will only be 10 bits of resolution across the presumably non-linear sensor input.

I'm interested in disaggregating the data and hope to be able to see a few watts of a light going on or off even when the overall consumption is high.  I'm also thinking I might hack about with the PIC to have it send at a higher rate. (exploring this was the purpose of me opening the box in the first place).

Cheers
Rupert

**Comment by JackKelly** [comment]
Hi Rupert!

To answer your questions:

_Reception issues_
I'm as baffled as you;) A couple of thoughts (which may be irrelevant!):
- I have found that RF packets from CC transmitters can "collide" because the transmitters make no attempt to do collision avoidance or carrier detection (i.e. the transmitters just talk over each other).  Pairs of transmitters drift in and out of sync with each other (because they don't wait precisely 6 seconds before transmitting: that 6 seconds varies by a few hundred milliseconds between units).  The end result is that you can get intermittent "blackouts" for one or two transmitters lasting an hour.
- I can't imagine how it would be possible to damage the aerial by taking the unit apart but I guess something might have gone wrong?  Not sure!
- You could try adding an external aerial like [this guy](http://www.flickr.com/photos/netcompsys/sets/72157625058490399/with/5089623817/) has done!  I haven't tried it myself!

_12 bits of data per sensor/clamp?_
If you have good reason to believe something is wrong on the wiki then please feel free to update the wiki!  I think there might be a typo on the wiki... I think the sensor data is 15 bits per sensor.

_Have you found how the ADC's are wired to the sensor?_
I haven't, sorry.

_I'm interested in disaggregating the data_
Disaggergation, you say?!  We should talk more about this!  I'm 12 months into a Ph.D. on "smart meter disaggregation"!  My aim is to build an open-source disaggregation system (implemented in Python and C++) which hopefully will achieve state-of-the-art performance.  I hope to have the first working iteration done by early 2013 (although the first version may not quite achieve state-of-the-art performance!)  My (slightly out of date) PhD abstract [is here](http://jack-kelly.com/about) and some initial papers are [here](http://jack-kelly.com/about).  And my reference library database on disaggregation is [available online on Zotero](https://www.zotero.org/jack_kelly/items/collectionKey/A2B7QF6C).  Disaggregation is a really interesting area, I'm sure you'll have lots of fun with it!

**Comment by JackKelly** [comment]
A quick thought.. 

If you want to raise the sample rate then instead of hacking the CurrentCost transmitter, you might find it easier to use an Open Energy Monitor (based on an Arduino)

**Comment by GrahamM** [comment]
I've updated the wiki for the currentcost whole house transmitter. I'd ended up getting the description wrong, although the bit column was correct. Each of the three sensors reported are 15bits in value, so the whole house sensor could technically report 3 x 32767W or 98301W. The testing I did indicated that the EnviR can indeed deal with that and reports 98.3KW when all three sensors are saturated.

Apologies for the mistake!

**Comment by GrahamM** [comment]
Alas, I don't know the wiring for the CT based whole house transmitter, as I don't have one to play with. I only have the optismart transmitter. I guess someone will have to examine the board and trace the circuit to find out if there's any tricks that have been implemented (like switching elements to increase the apparent ADC range).

**Comment by meesern** [comment]
Hi,
Thanks, I'll check out the Open Energy Monitor.  Thanks Graham for the update, 15bits at 1 watt sounds better - I've not had chance yet but I should be able to see from the PCB how the sensor is going into the ADC's.  I imagine that if there is only 10 bits of resolution overall that small signals like a light going on will be lost when the kettle is boiling.  I'll let you know what I find.  

Jack I'm glad (in a way) you can't think of any reason for the short range.  I certainly can't.  Most of all thanks for the links.  That's a really nice article on disaggregation, we should talk more.  I'll drop a line to your blog.

**Comment by GrahamM** [comment]
Loss of small signals would be true, although it is a CT clamp, so I'm not hopeful for accuracy. In my experience, CT clamps can be up to 25% out from the real consumption, especially when the power factor is not 1. In that case, the small signal from a light bulb might not be such a big deal!

**Comment by meesern** [comment]
Yes, a fair point!  Although in my case I'm not so concerned about the accuracy as the signal trace.  I don't much mind what the accuracy or even the non-linearities are so long as all events are actually there in the data in some way.

**Comment by JackKelly** [comment]
Is it OK if we close this issue now?  (I'm starting to use the issue tracker during development now)

**Comment by meesern** [comment]
Sure, thanks.
